defaults:
  - _self_
  - model: mlp

exp_prefix: ''
exp_suffix: ''
use_tb: True
use_wandb: True

train_data_path: 'data/train_data.txt'
test_data_path: 'data/test_data.txt'

num_workers: 4
log_interval: 100
eval_interval: 3


