defaults:
  - model: mlp

exp_prefix: ''
exp_suffix: ''
use_tb: False
use_wandb: True

rootdir: '/Users/mac/Desktop/PENN/f1tenth-final-project'
train_data_path: 'data/train_data.txt'
test_data_path: 'data/test_data.txt'

seed: 0
num_workers: 8
device: 'cpu'
log_interval: 30
eval_interval: 1

save_checkpoint_interval: 10