defaults:
  - model: mlp

exp_prefix: ''
exp_suffix: ''
use_tb: False
use_wandb: False

rootdir: '/Users/mac/Desktop/PENN/f1tenth-final-project'
train_data_path: 'data/train_data.txt'
test_data_path: 'data/test_data.txt'

seed: 0
num_epochs: 1
num_workers: 0
device: 'cpu'
log_interval: 100
eval_interval: 3