# @package model
name: 'mlp'
state_dim: 9
action_dim: 2
state_out_dim: 5
history_len: 4
hidden_dim: 64

lr: 1e-3
lr_scheduler: 'StepLR'
lr_step_size: 8
lr_gamma: 0.5

batch_size: 128
num_epochs: 20

pinn: False
pinn_lambda: 1.0