# @package model
name: 'Transformer'
state_dim: 5
action_dim: 2
history_len: 10
hidden_dim: 128
nheads: 4
num_layers: 2

lr: 1e-3
lr_scheduler: 'StepLR'
lr_step_size: 10
lr_gamma: 0.5

batch_size: 64
num_epochs: 20

pinn: False
pinn_lambda: 1.0